### ISSUE TITLE
`key` shouldn't be passed in via props according to react checks

### ISSUE THREAD

**Issue by trajano** [Dean177/react-native-json-tree#164]
To whoever wants to maintain a fork of this feel free to take this patch

https://github.com/trajano/expo-experiments/blob/expo-52-try-3/patches/react-native-json-tree%2B1.3.0.patch

**Comment by Dean177** [comment]
If you open a pull request I will be happy to merge and release a new version

**Comment by trajano** [comment]
It may just be waiting a release https://github.com/Dean177/react-native-json-tree/commit/3ebe8551ef9beef0a42b1fd9ca47e6d0f0bf0d86 should've fixed the issue

**Comment by trajano** [comment]
Even this solves the other issue in my patch https://github.com/Dean177/react-native-json-tree/commit/5310fad8ce6ae28a9846d32cf5d1cf9feaa3922e

**Comment by mlazari** [comment]
> If you open a pull request I will be happy to merge and release a new version

@Dean177 I think this is the issue I fixed in https://github.com/Dean177/react-native-json-tree/pull/162 but it was not released yet.

**Comment by JustJoostNL** [comment]
@Dean177 are you able to create a new release? 😄

**Comment by techgerm** [comment]
Is there an update on when this can be released?

**Comment by Dean177** [comment]
Sorry for the delay, 1.4.0 has now been published

**Comment by iressler** [comment]
It looks like #161 & #162 didn't fix `JSONValueNode` having `defaultProps`. I've opened #165 with the relevant parts of the [patch](https://github.com/trajano/expo-experiments/blob/expo-52-try-3/patches/react-native-json-tree%2B1.3.0.patch) from @trajano
